### ISSUE TITLE
Ruby Style Guideのスタイルを遵守しましょう

### ISSUE THREAD

**Issue by YukiTamura14** [kmhitters/circle#68]
まずスタイルを遵守できているか、チェックをお願いします！
https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md#%E3%83%AC%E3%82%A4%E3%82%A2%E3%82%A6%E3%83%88

@YukiTamura14 
indent修正をしました。一応、その他確認しました。
もう一度DICブランチより確認お願いいたします。

**Comment by kmhitters** [comment]
- [ ] indent修正
blogs_controller
comments_controller
events_controller
passwords_contoroller

*原因→テキストエディタAtomが壊れているためにSublimeTextを一時的に使用している
こちらscaffoldで作成するprivateメソッドがindentがずれることを確認した。
